name: Frontend CI
on:
  push:
    branches:
      - develop
jobs:
  frontend-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install dependencies
        working-directory: Front/foro-academico
        run: npm ci
      - name: Build Angular App
        working-directory: Front/foro-academico
        run: npm run-script build-prod  # package.json -> "scripts"
      - name: Sonar
        if: success()
        uses: SonarSource/sonarcloud-github-action@v2 # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
